services:
  nginx:
    image: nginx:1.27.4
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./logs:/var/log/nginx
      - ./public:/app/public:ro
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
    networks:
      - proxy-network

  certbot:
    image: certbot/certbot
    volumes:
      - ./certs:/etc/letsencrypt
      - ./certs-data:/var/lib/letsencrypt
      - ./logs:/var/log/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock  # опционально
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true
